spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dp-cliente?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # puede ser none, validate, update, create, create-drop según necesidad
    show-sql: true      # para mostrar las consultas SQL en consola
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

# Cambiar el puerto de la aplicación
server:
  port: 8081  # Cambia a cualquier puerto disponible, como 8081
