spring:
  application:
    name: dp-notificacion
  profiles:
    active: development
  config:
    import: optional:configserver:http://root:123456@localhost:7070

  mail:
    host: smtp.gmail.com
    port: 587
    username: reginaldobuendia@gmail.com  # Usa una variable de entorno para el correo electr칩nico
    password: "ceeqpnfrwtlkqlpq"  # Usa una variable de entorno para la contrase침a o la contrase침a de la aplicaci칩n
    protocol: smtp
    smtp:
      auth: true
      starttls:
        enable: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.mail: DEBUG   # Habilitar logging detallado para Spring Mail
    org.springframework.web: DEBUG    # Habilitar logging detallado para solicitudes web
