server:
  port: 8080

eureka:
  client:
    serviceUrl:
      #defaultZone: http://localhost:8090/eureka
      defaultZone: ${EUREKA_URI:http://localhost:8090/eureka}
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
      routes:
        - id: pd-inventario
          uri: lb://pd-inventario
          predicates:
            - Path=/movimientos/**
            - Path=/productos/**
        - id: dp-cliente
          uri: lb://pd-cliente
          predicates:
            - Path=/clientes/**
        - id: dp-licencias
          uri: lb://dp-licencias
          predicates:
            - Path=/licencias/**
        - id: pd-venta
          uri: lb://pd-venta
          predicates:
            - Path=/ventas/**
        - id: ms-facturacion
          uri: lb://ms-facturacion
          predicates:
            - Path=/facturas/**
