spring:
  application:
    name: auth-service
  profiles:
    active: development
  config:
    import: optional:configserver:http://root:123456@localhost:7070

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

jwt:
  secret: mi_clave_super_secreta_de_32_bytes_123456