server:
  port: 8087

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:mysql://localhost:3306/pd_authdb?useSSL=false&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect


jwt:
  secret: mi_clave_super_secreta_de_32_bytes_123456

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka
