server:
  port: 8083

spring:
  application:
    name: pd-venta
  datasource:
    url: jdbc:mysql://localhost:3306/pd_contacloud?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8090/eureka

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
  circuitbreaker:
    enabled: true

resilience4j:
  circuitbreaker:
    instances:
      clienteClient:
        registerHealthIndicator: true
        slidingWindowSize: 5
        failureRateThreshold: 50
      productoClient:
        registerHealthIndicator: true
        slidingWindowSize: 5
        failureRateThreshold: 50

management:
  endpoints:
    web:
      exposure:
        include: "*"
